### PR TITLE
Release pt-BR Brazilian (REAPER+SWS) v6.78

### PR DESCRIPTION
**Pull request by E-Deff**
Nota: Para versão Linux, download a partir de - https://stash.reaper.fm/tag/Language-Packs

### CODE REVIEW

**Comment by cfillion** [comment]
What's wrong with the Linux version?

**Comment by E-Deff** [comment]
Hi Christian,

I will use as an example the dialogs translated to [DLG_142]. See pics.

On Linux, many of the windows for text don't support every sentence like on Windows and Mac. So the sentence needs to be synthesized.

Kind regards,
Edison
________________________________
De: Christian Fillion ***@***.***>
Enviado: segunda-feira, 27 de março de 2023 23:48
Para: ReaTeam/LangPacks ***@***.***>
Cc: E-Deff ***@***.***>; Author ***@***.***>
Assunto: Re: [ReaTeam/LangPacks] Release pt-BR Brazilian (REAPER+SWS) v6.78 (PR #41)


What's wrong with the Linux version?

**Comment by cfillion** [comment]
Yeah, noticed the differences shortly after posting. I edited the previous message on GitHub with steps how to configure the ReaPack package to install the correct version depending on the user's OS.

**Comment by E-Deff** [comment]
IMHO, it would be interesting if in the Package editor we had in addition to the All platforms option, another option to select macOSX and Windows OS for example. And vice versa.

Until windows for translation in the Linux API, meets the same criteria as macOSX and Windows OS, or not.

Please, if you accept my suggestion, delete the 6.78 translation so I can later upload it to ReaPack for (macOSX and Windows OS) and another one for (Linux).

Best Regards,
Edison

________________________________
De: Christian Fillion ***@***.***>
Enviado: terça-feira, 28 de março de 2023 01:16
Para: ReaTeam/LangPacks ***@***.***>
Cc: E-Deff ***@***.***>; Author ***@***.***>
Assunto: Re: [ReaTeam/LangPacks] Release pt-BR Brazilian (REAPER+SWS) v6.78 (PR #41)


Yeah, noticed the differences shortly after posting. I edited the previous message on GitHub with steps how to configure the ReaPack package to install the correct version depending on the user's OS.

**Comment by E-Deff** [comment]
IMHO, it would be interesting if in the Package editor we had in addition to the All platforms option, another option to select macOSX and Windows OS for example. And vice versa.

Until windows for translation in the Linux API, meets the same criteria as macOSX and Windows OS, or not.

Please, if you accept my suggestion, delete the 6.78 translation so I can later upload it to ReaPack for (macOSX and Windows OS) and another one for (Linux).

Best Regards,
Edison
________________________________
De: Christian Fillion ***@***.***>
Enviado: segunda-feira, 27 de março de 2023 23:48
Para: ReaTeam/LangPacks ***@***.***>
Cc: E-Deff ***@***.***>; Author ***@***.***>
Assunto: Re: [ReaTeam/LangPacks] Release pt-BR Brazilian (REAPER+SWS) v6.78 (PR #41)


What's wrong with the Linux version?

**Comment by cfillion** [comment]
> IMHO, it would be interesting if in the Package editor we had in addition to the All platforms option, another option to select macOSX and Windows OS for example. And vice versa.

Yes. It is possible to configure the main langpack file to be installed only on Windows on macOS, and have a special version installed only on Linux. All in the same ReaPack package. (Demonstrated in the gif screencap above.)

This would make it fully transparent to the user as they would automatically get the correct version for their OS.

**Comment by E-Deff** [comment]
Hello Christian,

I think I'm blind, because I can't find the Gif.

Best regards,


________________________________
De: Christian Fillion ***@***.***>
Enviado: terça-feira, 28 de março de 2023 20:40
Para: ReaTeam/LangPacks ***@***.***>
Cc: E-Deff ***@***.***>; Author ***@***.***>
Assunto: Re: [ReaTeam/LangPacks] Release pt-BR Brazilian (REAPER+SWS) v6.78 (PR #41)


IMHO, it would be interesting if in the Package editor we had in addition to the All platforms option, another option to select macOSX and Windows OS for example. And vice versa.

Yes. It is possible to configure the main langpack file to be installed only on Windows on macOS, and have a special version installed only on Linux. All in the same ReaPack package. (Demonstrated in the gif screencap above.)

This would make it fully transparent to the user as they would automatically get the correct version for their OS.

**Comment by cfillion** [comment]
It's in this comment: https://github.com/ReaTeam/LangPacks/pull/41#issuecomment-1486126759.

**Comment by E-Deff** [comment]
Please, delete (REAPER+SWS) v6.78 #41

**Comment by E-Deff** [comment]
I did a test a little different from the Gif, One for (Mac & Win) another (Linux). Please see what you think...

**Comment by cfillion** [comment]
Both PR #42 and #43 modify the same file, so both cannot be released at the same time. I think making the package auto-select which file to install based on the user's OS is easier to use, but providing two separate packages and letting users pick the one they want is also an option. However in that case they need to have different filenames.

**Comment by E-Deff** [comment]
Hi Christian
Please see the info on the headers that will be present in the ReaPack for each LangPack file. See attached pics.

I think it works this way...

Best regards,
E. Deff
________________________________
De: Christian Fillion ***@***.***>
Enviado: quinta-feira, 30 de março de 2023 19:10
Para: ReaTeam/LangPacks ***@***.***>
Cc: E-Deff ***@***.***>; Author ***@***.***>
Assunto: Re: [ReaTeam/LangPacks] Release pt-BR Brazilian (REAPER+SWS) v6.78 (PR #41)


Both PR #42<https://github.com/ReaTeam/LangPacks/pull/42> and #43<https://github.com/ReaTeam/LangPacks/pull/43> modify the same file, so both cannot be released at the same time. I think making the package auto-select which file to install based on the user's OS is easier to use, but providing two separate packages and letting users pick the one they want is also an option. However in that case they need to have different filenames.

**Pull request closed without merging**
